# Configuración de la API CRUD existente
blueprints.crud.api.url=http://localhost:8080/api/v1/blueprints

# Configuración del servidor
server.port=8081

# Logging
logging.level.com.eci.blueprints.rt=DEBUG
